language: node_js
os:
- linux
- osx
node_js:
- 6
- 7
- 8
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/54f8a1e753f859f5ca1a
    on_start: never
    on_failure: change
deploy:
  provider: npm
  email: jimmy.aumard@gmail.com
  api_key:
    secure: mcThAS1T435rHU130oKbB8tS00MpqaCLHPsDr3CNf+Sd6zl74olq1yfLkyd15XTAB4PSMoL8ujwnFT5L5himHOV6U1TKvCJhPahG1zqwwry7e9CfLtjqer1vpZGsMZRk7mMFHehr0HYzmhp7hFD+ZW417HWRw+96Ru6MlMY4z47O4ko4VWO1Wwo+aY7UIWiy5qfMUYffC5f0RrGk+k2gjpUX0h5fpBo/d6+aQ2AE9/HjvZOMKxHK0qaIfYv1M4+986U6xyB3pYy3wEDUwsbm/E88FiSKjGUXeBdxLcDfPB6Qk4H4WR0WBDgYia+vvpjHlVbISDMLMQg9X9ufw1TAlJPPpVqK9FQjvR/T9347zyw6R72/pV97KjVuygxBJkGd9tF8ZAUqitgj+hUiblvDuCFGlXPjRsce/etVygnK+ht9DYU7hOFvrT+bGQrnGp0H/SeklgeOuvN4onrtFy9DEB1v7JaOaOaIGiRCis4ZBHqUj+wcutd7VhJDeoo2rn/nTnYLbOQ8Wjbbgai6DScnoBPcVBa3yCV6CMS+6+pNIN1foV9g9SW1fRqlnH4TAZJKScWJK6MU/3rqBSWDhegO/Fk2Qhr3/AT4TzHoCi3uzpAUbPSUQ3K2prs6x2U+AKMfHIVx7Qkl4OVO0k+zEM16X97d9cr6yTMI+An5CDBZeUU=
  on:
    tags: true
    repo: mylisabox/trailpack-chatbot
    node: 7
