language: node_js
os:
- linux
- osx
node_js:
- 6
- 7
- 8
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/54f8a1e753f859f5ca1a
    on_start: never
    on_failure: change
deploy:
  provider: npm
  email: jimmy.aumard@gmail.com
  api_key:
    secure: mRuUhQW43ula7YIm829u0nEAktr55xF7hntch0RmGYbJQ88wZz3Cl1w7suMj6rhwQ32zv60uNdrLMkFwYDt/C/8srFeeL82LYAJjKrQ0cUi5EJMvmKz9WIPiKWsdnAeqF4mcoSZNFv4Dh1RDCQb6qVsnP2Sost8auRWdRvpIOVD0YiwS6E883C8OCme0Hzr+eeMX6EBPUjc5LNJX70lSh1Mf7otQkWgTTdtcHEDVy1gmNYRTuy7HbYLz/UE8zBzZBWZLD/CTHfnbYZagb5Tjd6HskoQPF7OuJU0Cm38XCWzK7jwNdbAMtnOPtENrmJInIDiiLxVM90OqQhVyNvwtx0r5BT2bt3gRRWDGAYuRwsuvZSL7f+ZiII5FCKw896VsT3G+9/iGhWOMyaIY5XDOBs7JU8PGmJwyUaE5+nhgOBHLsyX8QadnY7vsuX+rU4W5Zo2GD2ROFTyKf+wJkgxWUEWdG15wboog8jkp0HMRgtvxysXgw784+bArJCGYMAixCLPhtMr2pSWVgf/b/033a+zzdSQzmwba5IXNCSbNKxvIxuWFpCXGVkOEsyxADsGt4TNaYy81kDa3dYkH37k1b7vnb7Hz1gvexJDVl6rpQEPcpOSrNR4mImoVIMqHk3j93GOA4f5tzEXb7pBPlxrY+knGSPEO0n2VF1FOefgbIpA=
  on:
    tags: true
    repo: mylisabox/trailpack-chatbot
    node: 7
