language: node_js
os:
- linux
- osx
node_js:
- 6
- 7
- 8
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/54f8a1e753f859f5ca1a
    on_start: never
    on_failure: change
deploy:
  provider: npm
  email: jimmy.aumard@gmail.com
  api_key:
    secure: gGDdfJqOjUkUL33pE1g6JKLSRds/ms3XeE/UGlbuTti+Wggtm1PTY7vsoFT4ShoQQe1RtjiSvWM1OxVTE7QyW3hWe7cdlo6OIpNlMAcDullowfftxOaUtumPOpCiqWUZfDEhXu3/40PUDVXjx9Z/eJWmrwx285wEn2Kz4RwdRjOuFMutOTK5BTL6TOs/THKszo9guoDHcOwxki+ol3pkD167G4CY9mJI9v3iNRVSpgRhYqUm3PEd77sNYa3scJRcBPFVn06IJC8NkMGvhmmhX8zPiSioMkiXcELR1jwvQGVTtRYbXhJisExcmiKn/guItJxVTSa2W0DXPPZYjIBA6cN8iSl+4Rdg987L+H7YWXDNWDkgBk7QhGRdeYl5B8Nw5VBEmCzeFNHkB8i/SncTo8ACF1ELaYDc1AGtstemHRoUxAC2gEwciOOraJz7sobf2Tc3T8Tucc9PaqrY9Zo5wIoRl8KJSxlLv8PZDyvmH+Bl5/9wQ+QjAkf93lRZZ7lY8NGOefupsSawREvhIpRdXcIlzCC/tDCUazRfKr7q3lB4FZKKxr+keBv0XdVU7Tal+Dy7KlLXTQDqwICgyJhB64aogjpOuneBBo2pt/+skpvaTqicR14NP+1woX851M99FagW/QNN4yyj83n6F7tZoP4e9Mf3+qtKJZL+diPrlws=
  on:
    tags: true
    repo: mylisabox/trailpack-chatbot
    node: 7
